spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32768/account-ob
    username: postgres
    password: password
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 30000
  liquibase:
    changeLog: db/changelog/root.yaml

dictionaries:
  currency:
    EUR: "Euro"
    USD: "US Dollar"
    RUB: "Russian Ruble"
    CNY: "Yuan"
    AED: "UAE Dirham"

clients-properties:
  initial-status: 1