server:
  port: 0

spring:
  application:
    name: account-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32768/account-ob
    username: postgres
    password: password
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 30000
  liquibase:
    changeLog: db/changelog/root.yaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

dictionaries:
  currency:
    EUR: "Euro"
    USD: "US Dollar"
    RUB: "Russian Ruble"
    CNY: "Yuan"
    AED: "UAE Dirham"

clients-properties:
  initial-status: 1