server:
  port: 0

spring:
  data:
    mongodb:
      database: clients
      uri: mongodb://localhost:27017
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


client-info:
  supported-countries: [ Indonesia, Russia, Kazakhstan ]