spring:
  cloud:
    gateway:
      routes:
        - id: account-api
          uri: lb://account-api
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/?(?<segment>.*), /$\{segment}
        - id: client-api
          uri: lb://client-api
          predicates:
            - Path=/client/**
          filters:
            - RewritePath=/client/(?<segment>.*), /$\{segment}